### PR TITLE
Create the login menu

### LINKED ISSUE #13: Implement the login menu
Take the design we've created and implement the login menu on the frontend

### PR DESCRIPTION
**Pull request by jstnf**
Implemented the login menu
- the login menu uses Google's API to login with Google accounts
- something something else....

May need to write some tests for this later on.

This pull request closes #13.

### CODE REVIEW

**Review by dramos2001 — APPROVED** [review]
I hate this

**Review by xcaracal — APPROVED** [review]
<333

**Review by lly022 — CHANGES_REQUESTED** [review]
This isn't good enough, needs more idk

**Review by lly022 — APPROVED** [review]
LGTM

**Review by dramos2001 — APPROVED** [review]
Your code is amazing!!

**Pull request merged**
